### ISSUE TITLE
Exactly TomIO, Do Not Give Up to My Project Sir

### ISSUE THREAD

**Issue by BBCByComcast** [BBCByComcast/Windroid#1]
BBCByComcast Maybe Acquire TomIO, Somebody Wanted Windows 11 in Termux Instead

That Why You Should...... _**Never Give Up to My Project**_ So You Can't Give Up
I Need TomIO for Making Windroid Project, If That Case About Sylirre And Twaik

Then You _**DO NOT**_ Need Busy Anymore, I am Acquiring Technical Bot So I Need it for Fix Coreland
![channels4_profile (1)](https://github.com/BBCByComcast/Windroid/assets/137778363/088b7f76-050f-4439-92f7-6c1558b95caa)

**Comment by TomJo2000** [comment]
I am not available to be "acquired",
I am a volunteer and hobbyist programmer, and I have no interest in contributing to this project.

***Cease and desist*** from contacting me about any such "acquisitions" again or I will be forced to block you.

**Comment by TomJo2000** [comment]
Additionally do not harass Syrlirre, twaik or any other Termux contributor about this either.
I do not wish to report your account for spam but you are leaving me very little choice in the matter.
